# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InOfffice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InOfffice
  pod "TOMSMorphingLabel", "~> 0.5"

  target 'InOffficeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InOffficeUITests' do
    # Pods for testing
  end

end
